import requests
from datetime import datetime

def fetch_subdomains(domain, api_key):
    url = f"https://api.securitytrails.com/v1/domain/{domain}/subdomains"
    headers = {
        "APIKEY": api_key
    }
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        data = response.json()
        return [f"{subdomain}.{domain}" for subdomain in data.get('subdomains', [])]
    else:
        print(f"Failed to fetch subdomains: {response.content}")
        return []

def create_adlist(domain, subdomains):
    today = datetime.now().strftime("%Y-%m-%d")
    header = f"""
# Adlist generated by DixLan
# Date of scan: {today}
# Data provided by SecurityTrails
# ===================================================================
"""
    
    hosts_entries = ["0.0.0.0 " + subdomain for subdomain in subdomains]
    content = header + "\n" + "\n".join(hosts_entries)
    filename = f"{domain}_adlist.txt"
    
    with open(filename, "w") as file:
        file.write(content)

    print(f"Adlist created with the name '{filename}'.")

def main():
    domain = input("Enter the domain name: ")
    api_key = ("Enter SecurityTrails API KEY : ")
    subdomains = fetch_subdomains(domain, api_key)
    create_adlist(domain, subdomains)

if __name__ == "__main__":
    main()
